### ISSUE TITLE
src/test-runners/detect.ts and src/test-runners/detect/ share a name; the alias gate models the directory but resolution picks the file

### ISSUE THREAD

**Issue by skywills** [nathapp-io/nax#1648]
## Summary

`src/test-runners/detect.ts` (a facade re-exporting from `./detect/*`) and `src/test-runners/detect/` (a directory with its own `index.ts`) both exist. Module resolution prefers the file, so `@/test-runners/detect` resolves to `detect.ts` — never to `detect/index.ts`.

Found while fixing #1647. Not a blocker there; those imports were left as deep relatives.

## Why it bites

**1. `check-alias-internals` models the wrong module.** `listBarrelDirs` registers `@/test-runners/detect` as a barrel because `src/test-runners/detect/index.ts` exists. But an import written as `@/test-runners/detect` yields `detect.ts`'s exports. The two disagree, so adding an export to `detect/index.ts` does *not* make it reachable at that specifier — the symbol appears to be barrelled but the import fails at typecheck:

```
src/execution/lifecycle/run-completion.ts(27,10): error TS2305:
  Module '"@/test-runners/detect"' has no exported member 'clearWorkspaceCache'.
```

That is the exact failure hit in #1647, and it is confusing precisely because the barrel *looks* correct on disk.

**2. The facade omits two symbols consumers need.** `detect.ts` re-exports `_workspaceDeps` (`:23`) but neither `discoverWorkspacePackages` nor `clearWorkspaceCache`. So four `src/` files reach into the directory by deep relative:

| File | Symbol |
|---|---|
| `src/context/engine/providers/code-neighbor.ts:14` | `discoverWorkspacePackages` |
| `src/cli/setup-analyze.ts:13` | `discoverWorkspacePackages` |
| `src/commands/detect.ts:26` | `discoverWorkspacePackages` |
| `src/execution/lifecycle/run-completion.ts:28` | `clearWorkspaceCache` |

**3. Three of those four are already avoidable.** `src/test-runners/index.ts:38` exports `discoverWorkspacePackages` from `./detect/workspace`, so `@/test-runners` is a legal path today that nobody uses. Only `clearWorkspaceCache` lacks one.

## Options

1. **Rename the facade** to `detect-api.ts`, or fold it into `detect/index.ts` and delete it. Removes the ambiguity at the source. Touches the importers in `src/test-runners/resolver.ts:26-27`, `src/test-runners/index.ts:24-25`.
2. **Add the two symbols to `detect.ts`** and repoint the four importers. Smallest diff, leaves the name collision in place for the next person.
3. **Repoint the three `discoverWorkspacePackages` importers at `@/test-runners`** and export `clearWorkspaceCache` there too. Uses the path that already works; still leaves the collision.
4. **Teach `check-alias-internals` to skip a directory barrel that a sibling file shadows**, so it stops advertising an unusable path. Worth doing regardless of 1-3, since it is the part that actively misleads.

Option 1 plus 4 is the clean end-state. Note `src/forge/detect.ts` is a separate module with no directory beside it and is unaffected.

## Acceptance criteria

- `@/test-runners/detect` unambiguously names one module.
- No `src/` file imports `test-runners/detect/workspace` by deep relative.
- `check-alias-internals` does not suggest a barrel path that resolution cannot reach.
- `bun run lint`, `bun run typecheck`, and `bun run test` stay green; the `check:import-cycles` baseline does not grow.

## Related

- #1647 — the deadlock fix that surfaced this.
